In [2]:
import numpy as np
import matplotlib.pyplot as plt


In [21]:
def getErrorForNthArgumentOfFunction(f, paramArray, indexOfToBeCalculatedErrorN, errorOfNthParam):
    eps = 1e-10 * np.longdouble(paramArray[indexOfToBeCalculatedErrorN])
    if isinstance(eps, np.ndarray):
        epsIs0 = (eps == 0).astype(int).astype(np.float64)
        eps += epsIs0 * 1e-10
    else:
        if eps == 0:
            eps = 1e-10
    eps = np.longdouble(eps)
    paramsWithEps = np.array(paramArray, dtype=np.longdouble)
    copiedParams = np.array(paramArray, dtype=np.longdouble)
    paramsWithEps[indexOfToBeCalculatedErrorN] += eps
    return (np.longdouble(f(*paramsWithEps)) - np.longdouble(f(*copiedParams))) * np.longdouble(errorOfNthParam) / eps

def getCombinedErrorForAllParamsOfFunction(f, paramArray, errorArray):
    return np.sqrt(np.sum([getErrorForNthArgumentOfFunction(f, paramArray, i, errorArray[i])**2 for i in range(len(paramArray))], axis=0))

def getWeightedMeanAndExternalUnsure(values, unsures):
    weights = 1/((unsures**2.0) * np.sum(1/(unsures**2.0)))
    weightedMean = np.dot(values, weights)
    extUnsure = np.sqrt((np.sum(np.dot(weights, (values-weightedMean) * (values -weightedMean))))/(len(values)-1))
    return weightedMean, extUnsure

In [41]:
a1_AValues = np.array([0.95, 2.23, 4.945])
a1_AValuesError = np.ones_like(a1_AValues) * 0.03
a1_RValues = np.array([10,30,100], dtype=np.float64)
a1_RValuesError = a1_RValues * 0.01

def a1_calcPotentiometerWiderstand(aValues, rValues):
    return ((10.0 - aValues) / (aValues)) * rValues

a1_potentiometerWiderstand = a1_calcPotentiometerWiderstand(a1_AValues, a1_RValues)
a1_potentiometerWiderstandErr = getCombinedErrorForAllParamsOfFunction(a1_calcPotentiometerWiderstand, np.array([a1_AValues
, a1_RValues]), np.array([a1_AValuesError, a1_RValuesError]))
print(a1_potentiometerWiderstand)
print(a1_potentiometerWiderstandErr)

a1_potentiometerWiderstandWeightedMean, a1_potentiometerWiderstandWeightedMeanError = getWeightedMeanAndExternalUnsure(a1_potentiometerWiderstand, a1_potentiometerWiderstandErr)

print("Widerstand: ({} +/- {})".format(a1_potentiometerWiderstandWeightedMean, a1_potentiometerWiderstandWeightedMeanError))

[ 95.26315789 104.52914798 102.22446916]
[3.4579123  2.089984   1.59691115]
Widerstand: (102.14704125820268 +/- 1.932691767533439)


In [48]:
def rToErr(r):
    return r * 0.01
def aToErr(a):
    return 0 * a + 0.03
a2_r = np.array([10.0,10.0,10.0,10.0], dtype=np.float64)
a2_rErr = rToErr(a2_r)
a2_a = np.array([9.38, 9.66, 9.61, 5.02])
a2_aErr = aToErr(a2_a)

a2_r2 = a1_calcPotentiometerWiderstand(a2_a, a2_r)
print(a2_r2)
a2_r2Err = getCombinedErrorForAllParamsOfFunction(a1_calcPotentiometerWiderstand, np.array([a2_a, a2_r]), np.array([a2_aErr, a2_rErr]))
print(a2_r2Err)



[0.66098081 0.35196687 0.40582726 9.92031873]
[0.03473171 0.03234108 0.0327369  0.15496182]
